spring.application.name=demo
server.port=7090
server.servlet.context-path=/api
# 邮件配置
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=3335914015@qq.com
spring.mail.password=emtwoiqwyotbchgc
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.ssl.enable=true